# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Argyrios Samourkasidis
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
url: "http://samourkasidis.info" # the base hostname & protocol for your site
twitter_username: argydis
github_username:  argysamo
disqus_username:

# Build settings
markdown: kramdown
relative_permalinks: false
#permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"


compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'

gems: ['jekyll/scholar', 'jekyll-twitter-plugin']
scholar:
  style: assets/mine.csl
  locale: en

  sort_by: year
  order: descending

  group_by: year
  group_order: descending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{ reference | replace_first: 'A. Samourkasidis', '<b>A. Samourkasidis</b>'}}"
  reference_tagname: article

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: true
  bibtex_filters:
  - superscript
  - latex

  details_dir:    bibliography
  details_layout: details.html



  query: "@*"
