# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Argyrios Samourkasidis
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is Argyrios (Argyris) Samourkasidis personal website. Argyris
  is a DevOps engineer, a researcher and has worked for 
  a FP7 European project (MODEXTREME). He is affiliated with Democritus
  University of Thrace (DUTH), and Wageningen University and ING in the Netherlands.
  He is a travel and computer enthousiast, contributing in Python projects
  in his free time.
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
url: "https://www.samourkasidis.info" # the base hostname & protocol for your site
twitter_username: argydis
github_username:  argysamo

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Build settings
markdown: kramdown
relative_permalinks: false
#permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"


compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'

gems: ['jekyll/scholar', 'jekyll-twitter-plugin']
scholar:
  style: assets/mine.csl
  locale: en

  sort_by: year
  order: descending

  group_by: type
  group_order: descending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib
  reference_tagname: dd

  replace_strings: true
  join_strings:    true

  bibtex_filters:
  - superscript
  - latex

  details_dir:    bibliography
  details_link: ""

  query: "@*"
