# General Jekyll Config
highlighter: rouge
url: http://samourkasidis.info
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]

gems: ['jekyll/scholar']

#springer-lecture-notes-in-computer-science

scholar:
  style: springer-lecture-notes-in-computer-science
  locale: en

  sort_by: year
  order: descending

  group_by: year
  group_order: descending

  source: ./_bibliography
  bibliography: references.bib

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: true
  bibtex_filters:
  - superscript
  - latex

  details_dir:    bibliography
  details_layout: details.html



  query: "@*"
